### ISSUE TITLE
Possible Server Timeout during change of Quantitation Type

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#10]
Filling bug on behalf of Patrick:

When changing the quantitation type for a gemma experiment, the "more edit options" button opens a new tab.  After changing the quantitation type and clicking save, the page starts to refresh and implement the changes.  The problem is that the process never resolves itself and eventually times out with a 502 error (Quant-Type Page).  Despite this, if you refresh the original tab after letting some time go by, the changes you made will  appear (Experiment Info Page).  This can be done even though the new tab is still open and appears to still be running its process.

My Observation: This is probably a server timeout case, where the database is taking a long time to process the change?

**Comment by tesar-stepan** [comment]
Possibly fixed by 184fbe1cc411faaef35b158788e5ca80a781a7ed
