### ISSUE TITLE
Assays page does not load bioassays table so outliers cannot be removed

### ISSUE THREAD

**Issue by cindycri** [ppavlidis/Gemma#12]
When trying to load the assays page for eeID 6136 (http://www.chibi.ubc.ca/Gemma/expressionExperiment/showBioAssaysFromExpressionExperiment.html?id=6136) the following error comes up:

Error during read
java.lang.RuntimeException:
Message: java.lang.NoSuchMethodException: ubic.gemma.analysis.preprocess.OutlierDetails.getBioAssayId()
Details:
ubic.gemma.util.EntityUtils.getId (72)
ubic.gemma.util.EntityUtils.getIdMap (99)
ubic.gemma.web.controller.expression.bioAssay.BioAssayController.getBioAssays (95)
org.springframework.cglib.proxy.MethodProxy.invoke (204)
org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint (698)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (150)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (166)
org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke (91)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (172)
org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept (631)
sun.reflect.NativeMethodAccessorImpl.invoke (57)
sun.reflect.DelegatingMethodAccessorImpl.invoke (43)
java.lang.reflect.Method.invoke (601)
org.directwebremoting.impl.ExecuteAjaxFilter.doFilter (34)
org.directwebremoting.impl.DefaultRemoter$1.doFilter (428)
org.directwebremoting.impl.DefaultRemoter.execute (431)
org.directwebremoting.impl.DefaultRemoter.execute (283)
org.directwebremoting.servlet.PlainCallHandler.handle (52)
... (truncated)
 
After clicking ok the table which shows the bioassays is blank. This has happened with a couple other experiments but I didn't make a note of which ones.

**Comment by tesar-stepan** [comment]
Already logged and taken care of as issue https://github.com/ppavlidis/Gemma/issues/11
Will be rolled out soon.

**Comment by tesar-stepan** [comment]
Keeping this issue open to prevent further duplicates in case anybody else encounters this problem.

**Comment by tesar-stepan** [comment]
Fixed in release 1.11 (commit 159c488e09314d84112a1fe29601f54497f7de1c)
