### ISSUE TITLE
Automatic reindexing of new ontologies upon Gemma start-up

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#2]
When Gemma is loaded at start-up, it downloads and parses ontologies (OWL). Interestingly, any changes to the new ontology model is not reflected on the system, until a forced reindexing of the ontologies takes place. My suspicion is that Gemma automatically loads the old index cache, which is rather counter-intuitive.

Automatically triggering a reindexing of the ontology cache at startup would be a simple fix (and it would work), though we could consider a more better way around this.

**Comment by ppavlidis** [comment]
There is already a closely related issue in the old tracker (4328, note dependent issues).

The reason we don't index every time is that 1) it's unnecessary if the ontology hasn't actually changed and 2) it takes a while. But it might be that the latter is not a big deal (I don't remember how long it takes, obviously depends on the size of the ontologies - remember we have many of them) in which case the necessity issue is not important.

**Comment by JacobsonMT** [comment]
As stated above, related to: Bug 4328 - Make ontology loading more robust and re-doable without app restart.

Partial fix for robustness was implemented in ppavlidis/baseCode/e2542271353e21d51ba04046ec6b7e89c7a674a1

Implementation of an admin function to allow refreshing of the ontologies (followed most likely by re-indexing) still in progress.

**Comment by tesar-stepan** [comment]
Found an even older bug report in the old tracker - 1031 - which should be also closed after work on this is done.

**Comment by tesar-stepan** [comment]
This is causing this bug: http://www.chibi.ubc.ca/faculty/pavlidis/bugs/show_bug.cgi?id=4457
Currently solved by manually re-indexing ontologies, but it should be automatised.

Proposed solution with @JacobsonMT :
Compare hashes of newly downloaded ontology file with the ones stored on disk. If they do not match, run re-index. No need to store the previous version of files either, just keep the original hashes in memory during the overwrite process.

**Comment by JacobsonMT** [comment]
Currently the only accessible means of updating ontology indices is doing them all at once. Will look into implementing a more fine-grained approach so we only reindex just those ontologies that have changed.
