### ISSUE TITLE
Indicate when a data set has a batch confound for diff. ex.

### ISSUE THREAD

**Issue by ppavlidis** [ppavlidis/Gemma#21]
A batch confound is when samples from different experimental conditions are in different sample batches. For example, all the drug treated samples were in one batch, all the controls are in another batch. Expression changes associated with drug cannot be confidently distinguished from batch effects.

When Gemma detects this, it refuses to do batch correction. However, we allow differential expression to proceed. Leaving aside the question of whether that's a good idea, the fact that there was a confound is not made clear to users.

The web page shows that there is a batch artifact (if one is detected), but not the fact there is a confound is not made visible. 

Decent backend support for this exists; see EEService.getBatchConfound, which is called by the EE controller  (loadExpressionExperimentDetails - populates this in ExpressionExperimentDetailsValueObject, though only as a string).

Example: GSE27628
http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=3321

I suggest two places to surface the batch confound informatin (at least):
1. GUI The EE web page, same spot where we note the batch artifact - user should see a warning
2. In the differential expression analysis result file, in the header.

This should probably also be made visible through the restAPI in places where users might not want to bother with such data sets, or would at least want to know about it.

Complications:

Sometimes we can use a subset analysis so the batches are treated as separate experiments, in which case the batch confound is made irrelevant (still might be good to know about). This has to be detected so the warnings we give aren't misleading.

The presence of the confound could be changed by edits to the experimental design or other processing, experiment splitting, sample removal, etc. so it has to be recomputed.

**Comment by nzllim** [comment]
Partially relevant info: For certain classes of experiments (when organism part or collection of materials are used), current curation standards require a subset by default, often times negating the effect of the batch confound, as mentioned by @ppavlidis.

**Comment by tesar-stepan** [comment]
I will start working on updating the EE Page and Diffexp results file.

Re: visibility in the API:
This information is not currently stored anywhere, and is computed every time an experiment details page is loaded. It seems that computing the batch confound is a fairly lengthy process ( _BatchConfound.test( ee )_ ), so adding it to an array of experiments would significantly slow down fetching of the list (e.g. in the API).
The solution would be to change the model of the EE to contain this information, and recompute when the experiment changes like @ppavlidis mentioned.
I would also have to run a script to populate the new variable for all existing experiments when the change is made.

Please discuss.

**Comment by ppavlidis** [comment]
Computing whether there is a confound requires just looking at the experimental design (not the data), but yes, this is pretty heavy if you do it for many experiments at once. So it makes sense to cache in some way.

Triggering recomputation of things in response to experimental design changes is tricky, because during editing designs there may be numerous individual edits in a short span of time. You might want to do updates on some sort of schedule rather than in response to every atomic edit to avoid churn (like: only allow it to be computed once within an hour, and recompute it for all recently edited experiments every night; having a "manual override" button to trigger it would also be good in case the curator wants to get it refreshed on demand.

If we establish some schedule like that to be smart about handling responses to experimental design changes, there are other things that we might want to recomputed, like outlier predictions.

**Comment by tesar-stepan** [comment]
Added to EE details page in release 1.16 (currently still calculated on request, but model changes are done as well).

**Comment by tesar-stepan** [comment]
There is a problem in the scheduler that will be fixed in the next hotfix. I will run the batch info recalculation manually on all the experiments that had their info not updated because of this bug afterwards.
