### ISSUE TITLE
LoadValueObject relevant methods in ExpressionExperimentService not populating isPublic field properly

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#23]
This bug is reproducible when signed in as Anonymous via SpringSupport. The isPublic field for EEVO's are not populated (all False) when using loadAllValueObjects or loadAllValueObjectsTaxon from ExpressionExperimentService.

**Comment by tesar-stepan** [comment]
I was experimenting with this before the last release, and populating this value properly proved to slow almost all parts of gemma that use the EEVOs (so basically all front end). 

I postponed the solution for this as it is part of a bigger problem in the rest api, that will require joining the ACL tables when loading the EEVOs. I will most likely be dealing with it this week.

**Comment by nzllim** [comment]
That's interesting, because when I'm signed in, the problem resolves itself. Didn't take note/time if there was a delay in the data fetching process though.

No rush for the fix, since it does not affect my workflow.

**Comment by tesar-stepan** [comment]
This has been somewhat addressed in recent commits containing some WIP on the API, although the isPublic property is still not behaving correctly.

**Comment by tesar-stepan** [comment]
Should be fixed by 789522838bab7e92053405ee4fd1cfd5721acabe - test on sandbox

**Comment by tesar-stepan** [comment]
Fixed in release 1.15
