### ISSUE TITLE
Dataset group editor page not loading experiments in a selected group

### ISSUE THREAD

**Issue by cindycri** [ppavlidis/Gemma#29]
Normally on the dataset group editor page (http://www.chibi.ubc.ca/Gemma/expressionExperimentSetManager.html) you can select a group in the left-most panel and the experiments in it are loaded in the right-most panel but they are not showing up. 
In the middle panel you can normally search for an experiment by its ID but the search results are also not showing up (the eeID I tried was 10879).

**Comment by tesar-stepan** [comment]
Fixed in release 1.16
