### ISSUE TITLE
Possible Duplication of Fields in DiffExResultSetSummaryValueObject

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#39]
@tesar-stepan 

There appears to be two pairs of get/set methods calling for an object that suspiciously suggest they're the same thing:
getqValue and getQValue

**Comment by tesar-stepan** [comment]
@nzllim That is very much the case, they do exactly the same thing. The "getQValue" is correct camel-case, so I would remove the other one, unless you have a preference.

**Comment by nzllim** [comment]
No preference. Let's remain consistent. :)

**Comment by tesar-stepan** [comment]
Will remove the "getqValue" and "setqValue" methods in the next update.
