### ISSUE TITLE
Updates to Apidocs

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#5]
@tesar-stepan @JacobsonMT 
This is just a reminder to have the apidocs for Gemma and BaseCode updated to the latest iteration. It would likely be useful to have Jenkins automatically compile the javadocs to the latest version.

If possible, I would also like to potentially fast-track this, to expedite migrating our curation annotations from GoogleDocs over to Gemma proper.

**Comment by JacobsonMT** [comment]
Apidocs for Gemma and BaseCode updated to latest versions. See:

http://www.chibi.ubc.ca/Gemma/resources/apidocs/
http://chibi.ubc.ca/faculty/pavlidis/basecode/apidocs/

Looking into automating their deployment as part of our release process.

**Comment by tesar-stepan** [comment]
Automated with the Jenkins site task, thanks to @JacobsonMT.
