### ISSUE TITLE
GO counts in Gene Page are incorrect.

### ISSUE THREAD

**Issue by nzllim** [ppavlidis/Gemma#7]
Example: http://www.chibi.ubc.ca/Gemma/gene/showGene.html?id=177349

The gene is associated with many GO terms in the GO Tab, but the count shown on the information page is 0 (wrong).

EDIT: Removed irrelevant information about multi-functionality.

**Comment by tesar-stepan** [comment]
Fixed on sandbox:
http://sandbox.chibi.ubc.ca/Gemma/gene/showGene.html?id=177349
